name: Edward Lui Films
favicon: null
layout_spectrum: 0.8489639933686703
typography_spectrum: 0.03844226477667689
title: Edward Lui Films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5939981085248291
  lightness: 0.06565289222635329
  saturation: 0.6658423370681703
  rhythmicContrast: 0.7759290533140302
purpose: []
